name: My CI workflow

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch: 

jobs:
  hello:
    name: My Hello Job
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello world 
        run: echo "Hello World"
      - name: Second steps
        run: echo "Second"

  goodbye:
    name: my goodbye job
    needs: hello
    runs-on: windows-latest
    steps:
      - run: echo "Goodbye" 
        

  test: 
    name: Test the Python package
    needs: lint
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - python-version: "3.13"
            platform: "macos-15"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install the package
        run: pip install .[test]
      - if: matrix.python-version == '3.14'
        name: Conditional steps
        run: echo "Using Python 3.14"
      - name: Run the tests
        run: pytest -vv


